name: Check Pdf Links
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: run script
        run: |
          python scrap/check_updates.py
        env:
          UNAM_URL: ${{ secrets.UNAM_URL }}
